// Generated by CoffeeScript 1.7.1
(function() {
  var square;

  square = function(x) {
    var i, j, _i, _results;
    if (typeof x !== 'number') {
      throw "" + x + " is not a number";
    }
    if (x !== Math.round(x)) {
      throw "" + x + " is not a integer";
    }
    _results = [];
    for (i = _i = 0; 0 <= x ? _i < x : _i > x; i = 0 <= x ? ++_i : --_i) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (j = _j = 0; 0 <= x ? _j < x : _j > x; j = 0 <= x ? ++_j : --_j) {
          _results1.push(print('*'));
        }
        return _results1;
      })());
    }
    return _results;
  };

  square(4);

}).call(this);
